version: "3.1"

services:
  pingaccess:
    image: pingidentity/pingaccess:5.3.0-edge
    env_file:
      - ~/.pingidentity/devops
    environment: 
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-FHIR-AS.git
      - SERVER_PROFILE_PATH=pingaccess
      - VERBOSE=false
      - PA_LOG_LEVEL=INFO
    ports:
      - 443:443
      - 9000:9000
    networks:
      - pingnet-dmz
      - pingnet

  pingfederate:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pingdirectory:636 -t 300 -- entrypoint.sh start-server
    env_file:
      - ~/.pingidentity/devops
    environment:
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-FHIR-AS.git
      - SERVER_PROFILE_PATH=pingfed
      - PF_BASE_URL={{PingFed BaseURL}}
      - PF_LOG_LEVEL=INFO
      - USER_BASE_DN=o=anyhealth.org
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

  pingdirectory:
    image: pingidentity/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    env_file:
      - ~/.pingidentity/devops
    environment:
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-FHIR-AS.git
      - SERVER_PROFILE_PATH=pingdir
      - USER_BASE_DN=o=anyhealth.org
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
                 
  console:
    image: pingidentity/pingdataconsole:${PING_IDENTITY_DEVOPS_TAG}
    env_file:
      - ~/.pingidentity/devops
    ports:
      - 8080:8080
    networks:
      - pingnet

networks:
    pingnet:
    pingnet-dmz: